[package]
name = "tap"
version = "0.1.0"
authors = ["npes-95 <npe.smith.95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_approx_eq = "1.1.0"
termion = "*"
